Managing frontend dependencies
alphagov/paas-team-manual pull request #446
Opened 2022-07-05 08:49 UTC by kr8n3r

What
----

Describe what you have changed and why.

How to review
-------------

Describe the steps required to test the changes.

Who can review
--------------

Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.

2022-07-08 12:15 UTC, AP-Hunt requested changes

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> +GOV.UK Platform as a service team has four major web apps that require regular maintenance:
Platform as a Service

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> + - tests run and if sucessful, a [tag is created](https://concourse.build.ci.cloudpipeline.digital/teams/main/pipelines/paas-admin/jobs/tag-releases)
Might be good to specify tag format for a bit of extra context?

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> +Merging is cli sign-only, no Github web UI click-merge.
"PR's merge commits must be signed with a team member's GPG key, which can be done using the GDS CLI tool (`gds git merge-sign alphagov/paas-admin PR_NUMBER`). Do not merge through the GitHub UI".

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> +Dependabot is set-up to raise dependecy pull-requests and security audits.
s/pull-requests/pull requests/

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> +which is documented in the [project's README](https://github.com/alphagov/paas-product-pages#review-static-build-production-build)
[the `paas-product-pages` README] may be a better link title here, because it'll make more sense in isolation for a screen reader.

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> +In addition to the upstream tech-docs-gem dependency there are some local Ruby dependencies. Dependabot will raise update pull request against all dependencies, but it's always best to check if a new
tech-docs-gem is the name of the package, so will want to be in back ticks IMO

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> +Some of the stragies to use when managing updates
strategies

2022-07-08 12:15 UTC, AP-Hunt commented on source/guides/manage_frontend_dependencies.html.md
> +If you're unsure about package changes, need to run tests (locally or against staging, etc) or wish to manually check everything is OK, Aal of these have the ability to run locally.
s/Aal/all/

2022-07-08 12:45 UTC, kr8n3r commented
thanks Andy! 
I think I've addressed all the comments

2022-07-11 10:32 UTC, AP-Hunt requested changes
Few bits n bobs

2022-07-11 10:40 UTC, kr8n3r commented
good thing I don't write words for a living

2022-07-12 15:34 UTC, schmie requested changes
LGTM - few typo-things

2022-07-12 15:34 UTC, schmie commented on source/guides/manage_frontend_dependencies.html.md
> +Pull request merge commits must be signed with a team member's GPG key, which can be done using the GDS CLI tool (`gds git merge-sign alphagov/paas-admin PR_NUMBER`).
Could mention that "team" is defined in `paas-cf`?

2022-07-12 15:34 UTC, schmie commented on source/guides/manage_frontend_dependencies.html.md
> +Product pages are a set of static pages built by [NextJS](https://nextjs.org/). It utilises NPM dependencies and will have many fewer dependecy updates than PaaS admin
```suggestion
Product pages are a set of static pages built by [NextJS](https://nextjs.org/). It utilises NPM dependencies and will have many fewer dependency updates than PaaS admin
```

2022-07-12 15:34 UTC, schmie commented on source/guides/manage_frontend_dependencies.html.md
> +Most packages will have some release notes. Event though they might use [semantic versioning (semver)](https://semver.org/), it doesn't mean a fix/patch update doesn't contain major changes.
```suggestion
Most packages will have some release notes. Even though they might use [semantic versioning (semver)](https://semver.org/), it doesn't mean a fix/patch update doesn't contain major changes.
```

2022-07-12 15:48 UTC, kr8n3r commented on source/guides/manage_frontend_dependencies.html.md
> +Pull request merge commits must be signed with a team member's GPG key, which can be done using the GDS CLI tool (`gds git merge-sign alphagov/paas-admin PR_NUMBER`).
linked to it

2022-07-13 13:07 UTC, schmie approved these changes

2022-07-15 14:28 UTC, merged