Update deployment upgrade guide
alphagov/paas-team-manual pull request #457
Opened 2022-09-01 10:47 UTC by schmie

What
----

- Updated the cf-deployment upgrade guide
- Moved the buldpack upgrade guide into its own section

How to review
-------------

- Code/text review
- Middleman 

Who can review
--------------

not @schmie

2022-09-02 10:44 UTC, cadmiumcat commented on source/guides/upgrade_cf-deployment.html.md
> +1. Separate the upgrade of cf-deployment and/or stemcells from the upgrade of Bosh. Upgrades can cause problems and our experience is that it is difficult to be certain about the cause of those probl
This could be confusing if you don't have the context of how we used to do updates.
To "separate" the bosh upgrade, means creating a story for it, pointing at the correct upstream in the [manifest in paas-bootstrap](https://github.com/alphagov/paas-bootstrap/tree/main/manifests/bosh-manifest) and deploying it to a dev environment. Some of the steps that follow, but not all, apply to it.

Do we need a  specific section on upgrading Bosh?

2022-09-02 12:01 UTC, AP-Hunt commented on source/guides/upgrade_cf-deployment.html.md
> +1. Run the pipeline with the updated cf-deployment branch and make sure all acceptance tests have passed. This is important because the development environment might previously have been used to test
```
gds aws paas-dev-admin -- make dev01 pipelines BRANCH=UPGRADE_BRANCH_NAME SLIM_DEV_DEPLOYMENT=false
```

Where `UPGRADE_BRANCH_NAME` is the name of the branch containing the upgraded version

2022-09-02 12:01 UTC, AP-Hunt commented on source/guides/upgrading_CF,_bosh_and_stemcells.html.md
> ----
How come we deleted this guidance?

2022-09-02 12:57 UTC, cadmiumcat commented on source/guides/upgrade_buildpacks.html.md
> +Once the buildpack-upgrading PR has been created in the paas-cf repo (usually done
UTC - so it was 10am on Monday

2022-09-05 08:16 UTC, cadmiumcat commented on source/guides/upgrade_buildpacks.html.md
> +Send an email to users following [the upgrade template](/team/notifying_tenants/#cf-upgrade).
Using paas-announce
```suggestion
Send the email to users from the [GOV.UK PaaS Announce Google Group](https://groups.google.com/a/digital.cabinet-office.gov.uk/g/gov-uk-paas-announce).
```
I think the upgrade template link doesn't provide useful information - it just links back to here

2022-09-05 08:25 UTC, cadmiumcat commented on source/guides/upgrade_cf-deployment.html.md
> +1. Confirm that the process for [rotating credentials](https://team-manual.cloud.service.gov.uk/team/rotating_credentials/) still works and does not cause additional downtime during deployments. You
how would I spot that it _has_ caused "additional downtime"?

2022-09-05 08:28 UTC, cadmiumcat commented on source/guides/upgrade_cf-deployment.html.md
> +1. Confirm that the process for [rotating credentials](https://team-manual.cloud.service.gov.uk/team/rotating_credentials/) still works and does not cause additional downtime during deployments. You
This points to User Impact dashboards in prod, but at this point we're looking at a dev environment. As far as I can tell, we don't have the same dashboards in dev

2022-09-08 12:26 UTC, schmie commented on source/guides/upgrading_CF,_bosh_and_stemcells.html.md
> ----
File renamed to upgrade_buildpacks as CF content moved out of the file as per https://github.com/alphagov/paas-team-manual/pull/457/commits/533755fdde40e9b2abe3155e98826d9f8c8e3646

2022-09-08 12:46 UTC, schmie commented on source/guides/upgrade_buildpacks.html.md
> +If you are doing a platform upgrade, you should upgrade the buildpacks to at least the versions included in the cf-deployment version being deployed.
Removed.

2022-09-09 17:17 UTC, schmie commented on source/guides/upgrade_cf-deployment.html.md
> +1. Confirm that the process for [rotating credentials](https://team-manual.cloud.service.gov.uk/team/rotating_credentials/) still works and does not cause additional downtime during deployments. You
Yeah, I was not sure about this one - I do not think anything has broken the certificate rotation in a long while - at least I have not context on where this line came from (though it was useful to keep, but now have doubts). Should be remove this?

2022-09-16 08:00 UTC, cadmiumcat commented on source/guides/upgrade_cf-deployment.html.md
> +1. Confirm that the process for [rotating credentials](https://team-manual.cloud.service.gov.uk/team/rotating_credentials/) still works and does not cause additional downtime during deployments. You
Yeah, I'm removing this

2022-09-16 14:16 UTC, AP-Hunt requested changes
A few small changes but this is otherwise absolutely excellent

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_bosh.html.md
> +1. Make sure the current branch of `paas-bootstrap` deployed by the `create-bosh-concourse` pipeline to the environment is `main`, and has been run with the latest commit. If not, do it yourself.
Would be a useful reminder to lay out the command for that

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_bosh.html.md
> +1. When the `paas-bootstrap` pipeline finishes, run the `create-cloudfoundry` pipeline, making sure you are using the `main` branch of `paas-cf`.
Do we still have the issue of needing to run the deploy concourse job twice sometimes, because concourse rolls itself?

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_bosh.html.md
> +1. Pause the `create-cloudfoundry` pipeline in `staging`, `prod` and `prod-lon`. You can do this by pausing the `pipeline-lock` job for each of them in Concourse.
Ensure a deploy isn't going out before you start

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_bosh.html.md
> +1. Merge the PR using the gds-cli, which allows for merge signing:
Suggest "Merge-sign the PR. The gds-cli has a useful utility for this" in order to make it clear that merge signing is mandatory.

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_bosh.html.md
> +1. Trigger the `create-bosh-concourse` pipeline in `staging`. You can do this by triggering a new build of the `init-bucket` job in Concourse. When it finishes successfully, do the same for the prod
In `staging`, `prod` and `prod-lon`

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_buildpacks.html.md
> +   supplying highlights section by section when prompted by the script. Highlights are e.g. breaking changes, version deprecations, etc.
Also new versions

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_cf-deployment.html.md
> +1. Find out the correct version to upgrade to by checking the [cf-deployment releases documentation](https://github.com/cloudfoundry/cf-deployment/releases). Choose a recent stable release, but try t
Not sure what's meant by this

> Make also sure the release notes look like they will not introduce bugs.

Aren't bugs inherently unexpected?

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_cf-deployment.html.md
> +1. If you have issues in the releases of cf-deployment, consider overriding the release version with an [ops file](https://bosh.io/docs/cli-ops-files/).
Can you give an example of an issue you might have that I might need to solve with an ops file change?

2022-09-16 14:16 UTC, AP-Hunt commented on source/guides/upgrade_cf-deployment.html.md
> +If all the above tests pass, merge the PR using the gds-cli, which allows for merge signing:
Same are previous comment on merge signing

2022-09-20 15:19 UTC, cadmiumcat commented on source/guides/upgrade_cf-deployment.html.md
> +1. Find out the correct version to upgrade to by checking the [cf-deployment releases documentation](https://github.com/cloudfoundry/cf-deployment/releases). Choose a recent stable release, but try t
That's an excellent point. It sounded right when I read it 😆 
I will remove the statement

2022-09-21 07:54 UTC, cadmiumcat commented on source/guides/upgrade_cf-deployment.html.md
> +1. If you have issues in the releases of cf-deployment, consider overriding the release version with an [ops file](https://bosh.io/docs/cli-ops-files/).
yaaas! That time I had to add one for dynamic asgs being enabled by default

2022-09-22 10:56 UTC, AP-Hunt commented on source/guides/upgrade_bosh.html.md
> +1. When the `paas-bootstrap` pipeline finishes, run the `create-cloudfoundry` pipeline, making sure you are using the `main` branch of `paas-cf`.
I think if we don't recall fixing (and I call trying and failing), that we should explicitly mention that it could happen.

2022-09-22 12:44 UTC, AP-Hunt approved these changes

2022-09-23 07:43 UTC, merged